[package]
name = "btox"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
itsuki = "0.1.2"
ratatui = { version = "0.26.1", features = ["all-widgets"] }
uuid = { version = "1.8.0", features = ["v4", "fast-rng"] }
